using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GitTui.Generators;

[Generator]
public class LocalizationKeysGenerator : IIncrementalGenerator
{
    private const string ReferenceLangFileName = "lang.en.xml";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<string?> langFileContents = context.AdditionalTextsProvider
            .Where(file => Path.GetFileName(file.Path) == ReferenceLangFileName)
            .Select((file, cancellationToken) => file.GetText(cancellationToken)?.ToString());

        context.RegisterSourceOutput(langFileContents, GenerateLocalizationKeys);
    }

    private static void GenerateLocalizationKeys(SourceProductionContext context, string? content)
    {
        if (string.IsNullOrEmpty(content))
            return;

        XDocument document = XDocument.Parse(content);
        List<string> keys = document.Root?
            .Elements("trad")
            .Select(element => element.Attribute("name")?.Value)
            .Where(name => !string.IsNullOrEmpty(name))
            .Select(name => name!)
            .ToList() ?? [];

        StringBuilder source = new();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("namespace GitTui.Utils;");
        source.AppendLine();
        source.AppendLine("public static class LocalizationKeys");
        source.AppendLine("{");

        foreach (string key in keys)
            source.AppendLine($"    public const string {key} = \"{key}\";");

        source.AppendLine("}");

        context.AddSource("LocalizationKeys.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}